[build]
  command = "npm run build"
  publish = "dist"
  base = "frontend"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[functions]
  node_bundler = "esbuild" 
